# Golden Rigma coloscheme named after a ravishing book by Vsevolod Sysoev.
# URL: https://github.com/shved/golden-rigma

type = "gold"
constant = "harvest-gold"
number = "harvest-gold"
string = "harvest-gold"
comment = "slate-gray"
variable = "gold"
"variable.builtin" = "snow"
"variable.parameter" = "snow"
"variable.property" = "snow"
punctuation = "snow"
"punctuation.delimiter" = "snow"
"punctuation.bracket" = "snow"
keyword = "snow"
operator = "snow"
function = "snow"
"function.builtin" = "snow"
"function.macro" = "snow"
tag = "harvest-gold"
namespace = "snow"
attribute = "gold"
constructor = "gold"
module = "gold"
special = "snow"

"ui.background" = { bg = "darker" }
"ui.cursor" = { fg = "gold", bg = "dark" }
"ui.cursor.match" = { fg = "gold", bg = "dark" }
"ui.cursor.insert" = { fg = "gold", bg = "dark", modifiers = ["slow_blink"] }
"ui.cursor.select" = { fg = "snow", bg = "gold" }
"ui.linenr" = "slate-gray"
"ui.linenr.selected" = { fg = "tiger" }
"ui.statusline" = { fg = "snow", bg = "dark" }
"ui.statusline.inactive" = { fg = "dim", bg = "dark" }
"ui.popup" = { fg = "snow", bg = "dim" }
"ui.window" = { fg = "snow", bg = "dim" }
"ui.help" = { fg = "snow", bg = "dim" }
"ui.text" = "snow"
"ui.text.focus" = "silver"
"ui.menu" = { fg = "snow", bg = "dark" }
"ui.menu.selected" = { fg = "silver", bg = "dim" }
"ui.selection" = { bg = "steel" }
"ui.virtual.whitespace" = "steel"
"ui.virtual.ruler" = { bg = "steel" }
"ui.virtual.inlay-hint" = { fg = "steel", modifiers = ["italic"] }

hint = "royal-blue"
info = "gold"
warning = "tiger"
error = "lilly"

"diagnostic.hint" = { underline = { style = "curl", color = "royal-blue" } }
"diagnostic.info" = { underline = { style = "curl", color = "gold" } }
"diagnostic.warning" = { underline = { style = "curl", color = "tiger" } }
"diagnostic.error" = { underline = { style = "curl", color = "lilly" } }
"diagnostic.unnecessary" = { modifiers = ["dim"] }
"diagnostic.deprecated" = { modifiers = ["crossed_out"] }

"diff.plus" = { fg = "green" }
"diff.delta" = { fg = "tiger" }
"diff.minus" = { fg = "berberis" }

"ui.statusline.normal" = { bg = "bilberrie" }
"ui.statusline.insert" = { bg = "lilly" }
"ui.statusline.select" = { bg = "lotus" }

# "markup.heading" = { fg = "purple", modifiers = ["bold"] }
# "markup.list" = "cyan"
# "markup.bold" = { fg = "orange", modifiers = ["bold"] }
# "markup.italic" = { fg = "yellow", modifiers = ["italic"] }
# "markup.strikethrough" = { modifiers = ["crossed_out"] }
# "markup.link.url" = "cyan"
# "markup.link.text" = "pink"
# "markup.quote" = { fg = "yellow", modifiers = ["italic"] }
# "markup.raw" = { fg = "fg" }

[palette]
gold = "#FFD700"
snow = "#FFFAFA"
silver = "#C0C0C0"
dim = "#808080"
dark = "#666666"
darker = "#333333"

bilberrie = "#4169E1"
lilly = "#FF6347"
lotus = "#C71585"

tiger = "#FF8C00"
berberis = "#DC143C"
green = "#228B22"

golden-rod = "#DAA520"
harvest-gold = "#DA9100"
sea-shell = "#FFF5EE"
ivory = "#FFFFF0"
honey = "#CB8E00"
white-smoke = "#F5F5F5"
steel = "#B0C4DE"
light-yellow = "#FFFFE0"
royal-blue = "#4169E1"
blue2 = "#1E90FF"
coral1 = "#FF7F50"
deep-pink = "#FF1493"
sky-blue = "#00BFFF"
dark-orchid = "#9932CC"
orchid = "#DA70D6"
salmon = "#FA8072"
crimson-red = "#DC143C"
blue-violet = "#8A2BE2"
yellow-green = "#9ACD32"
burly-wood = "#DEB887"
bear-brown = "#B3632B"
dark-golden-rod = "#B8860B"
slate-gray = "#708090"
bee-hive = "#E2ED47"
